### Day 1
#### part A

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
infile="01a_input.txt"

In [22]:
vals=np.loadtxt(infile)

In [19]:
# compute 2020-vals
valsinv=2020-vals

# let n1+n2=2020
# n1 (and n2) is in vals, but then n1=2020-n2 (and n2=2020-n1) is also in valsinv
nrs=np.intersect1d(vals,valsinv) # len(nrs)=2 since the role of n1 and n2 can be flipped
nrs

array([ 144., 1876.])

In [20]:
# final result
nrs[0]*nrs[1]

270144.0

#### part B

In [23]:
infile="01b_input.txt"

In [24]:
vals=np.loadtxt(infile)

In [60]:
# repmat with vals vector along one dimension, repeated along 2nd and 3rd dimension
mat=np.tile(vals,(len(vals),len(vals),1)) # shape=200x200x200

In [56]:
# the vals value here change along the 2nd or 3rd dimension
mat2=np.moveaxis(mat,[0,1,2],[1,2,0])
mat3=np.moveaxis(mat,[0,1,2],[2,0,1])

In [58]:
# summing up the 3 matrices is equal to computing all possible sums
matsum=mat+mat2+mat3
idxs=np.argwhere(matsum==2020)
idxs

array([[ 24,  48, 181],
       [ 24, 181,  48],
       [ 48,  24, 181],
       [ 48, 181,  24],
       [181,  24,  48],
       [181,  48,  24]], dtype=int64)

In [61]:
idx=idxs[0]
idx

array([ 24,  48, 181], dtype=int64)

In [65]:
a=vals[idx[0]]
b=vals[idx[1]]
c=vals[idx[2]]
print(a,b,c)

513.0 512.0 995.0


In [66]:
# final result
a*b*c

261342720.0