### Day 10
#### part A

In [1]:
import numpy as np

In [2]:
infile="10a_input.txt"

In [3]:
vals=np.loadtxt(infile)
vals=np.sort(vals)
vals[0]

1.0

In [13]:
diffs=np.diff(vals)
diffs

array([1., 3., 3., 1., 1., 1., 3., 3., 3., 1., 1., 1., 1., 3., 3., 1., 1.,
       1., 1., 3., 1., 1., 1., 3., 3., 1., 1., 1., 1., 3., 1., 1., 1., 1.,
       3., 3., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 3., 1.,
       1., 1., 1., 3., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3.,
       1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1.,
       1., 3., 1., 3., 3., 3., 1., 1., 3., 3., 1.])

In [5]:
count1=np.count_nonzero(diffs==1)
count3=np.count_nonzero(diffs==3)

In [6]:
# final result
(count1+1)*(count3+1)
# first +1: vals[0]- chargingoutlet(0)
# second +1: device adapter is diff=3

2040

#### part B

In [7]:
# observation: there are no 2's in the diff vector. which seems to be a delibarate choice

In [8]:
# include the first jolt
diffsext=np.concatenate((np.array([1]),diffs))
diffsext

array([1., 1., 3., 3., 1., 1., 1., 3., 3., 3., 1., 1., 1., 1., 3., 3., 1.,
       1., 1., 1., 3., 1., 1., 1., 3., 3., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 3., 3., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 3.,
       1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 1.,
       3., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1.,
       1., 1., 3., 1., 3., 3., 3., 1., 1., 3., 3., 1.])

In [14]:
# find lengths of consecutive 1's stretches: here adapters can be skipped
lengths=[]
curlen=0
for idx in range(len(diffsext)):
    if diffsext[idx]==1:
        curlen+=1
    else:
        if curlen!=0:
            lengths.append(curlen)
        curlen=0
# append the last one
if curlen!=0:
    lengths.append(curlen)
lengths=np.array(lengths)
lengths    


array([2, 3, 4, 4, 3, 4, 4, 4, 4, 3, 4, 2, 4, 4, 4, 4, 4, 3, 1, 2, 1])

In [15]:
# possible re-arrangements for repeated 1's:
# 1    -> 1 (1 option)
# 11   -> 11,2 (2 options)
# 111  -> 111,12,21,3 (4 options)
# 1111 -> 1111,112,121,211,13,31,22 (7 options)

In [16]:
# longest stretch is 4 1's
cnt1=np.count_nonzero(lengths==1)
cnt2=np.count_nonzero(lengths==2)
cnt3=np.count_nonzero(lengths==3)
cnt4=np.count_nonzero(lengths==4)
print(cnt1,cnt2,cnt3,cnt4)

2 3 4 12


In [18]:
# final result
1**cnt1 * 2**cnt2 * 4**cnt3 * 7**cnt4

28346956187648